#!/usr/sbin/nft -f

table ip meridian {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # Autoriser le trafic de bouclage
        iifname "lo" accept

        # Autoriser les connexions établies et liées
        ct state established,related accept

        # Autoriser SSH uniquement depuis 192.168.56.0/24
        ip saddr 192.168.56.0/24 tcp dport 22 ct state new accept
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}

